### ISSUE TITLE
em-form-group in beta

### ISSUE THREAD

**Issue by mcobery** [piceaTech/ember-rapid-forms#114]
Does the em-form-group work in the latest beta release (`1.0.0-beta6`)?

In the following template, the second `em-text` displays and only the label `test` displays for the `em-form-group`.
```
{{#em-form model=loginModel submitButton=false}}
  {{#em-form-group label="test"}}
    {{em-text label="Comment" property="comment" rows=3}}
  {{/em-form-group}}
  {{em-text label="Comment" property="comment" rows=3}}
{{/em-form}}
```
Any help would be appreciated.  Form groups worked in this manner in the last release we used, `0.7.2`

**Comment by GCorbel** [comment]
It seems you're right. The reason is because of [this file](https://github.com/piceaTech/ember-rapid-forms/blob/master/addon/templates/components/form-group.hbs). It use `form-group-control` and `mainComponent.htmlComponent` is "erf-html-input". "html-input" has not yield inside and it doesn't make sense.

I don't understand why `form-group` use `form-group-control`. I don't think it's useful. Maybe @spruce can give me his opinion.

Thanks for reporting.

**Comment by GCorbel** [comment]
Ok @spruce , I understood. I will give a try tomorrow.

**Comment by GCorbel** [comment]
@mcobery can you check the PR #116 and tell me if it works. Thanks.
