### ISSUE TITLE
support for form without model

### ISSUE THREAD

**Issue by ballPointPenguin** [piceaTech/ember-rapid-forms#71]
I'm having trouble using ember-rapid-forms for my login form.
The form has inputs for 2 properties: email and password, but these are properties on my login controller, not on a model. If model is null, the html-input component causes the following error:
```
Uncaught Error: Property set failed: object in path "mainComponent.model" could not be found or was destroyed.
```

It would be nice if the form could track the values on the controller instead of on the model.

**Comment by asermax** [comment]
You always have to provide a model to the `form` afaik. 
In this case you could give the controller as the model for your form, but using `controller` on a template has been deprecated in Ember 1.1x and probably removed on Ember 2.x.
Another option (which I'm using on an application) is doing the following on your route:

```
import Ember from 'ember';
import EmberValidations from 'ember-validations';

var LoginData = Ember.Object.extend(EmberValidations, {
  email: null,
  password: null,

  validations: {
    ...
  },
});

export default Ember.Route.extend({
  model: function() {
    return LoginData.create({container: this.container});
  }
});
```

Note the `container` parameter when creating the object; this is a must if you're using `EmberValidations` since it resolves the validators through it.
I'm not 100% this is the ideal solution but is what we came up with when adapting our application to Ember 2.x + rapid forms

**Comment by ballPointPenguin** [comment]
I see.
Thank you for the response. There seems to be several ways to go about getting parameters in/out of a component that are not necessarily bound to a model. When I replace my login controller with a routable component in the future, I expect I will be passing attrs from the parent component to the child component.
In any case, I would think that using a form with values that are not on any model is a pretty common story.
For now, I will just roll my own form component to accomplish this.
